const app = document.querySelector('#app');
const params = new URLSearchParams(location.search);
const currentPersona = ['simon', 'alex', 'sarah'].includes(params.get('persona')) ? params.get('persona') : 'simon';

const people = {
  simon: {
    name: 'Simon', initials: 'S', title: 'Your retirement outlook', icon: '◔',
    nudge: 'Based on the assets and retirement income we currently know about, your illustrative plan may have a S$2,000 monthly income gap.',
    summary: 'You are approaching retirement. A short review now can help you understand what may affect your future monthly income.',
    signals: ['You are 55 and indicated a retirement horizon of 10 years.', 'Known CPF, investments and insurance have been included in this scenario.', 'Your assumed lifestyle income is higher than the retirement income currently projected.'],
    fields: [
      { key:'desired', label:'Desired monthly retirement income', min:4000, max:10000, step:500, prefix:'S$', value:7000 },
      { key:'forecast', label:'Forecast monthly retirement income', min:2000, max:8000, step:500, prefix:'S$', value:5000 },
      { key:'years', label:'Years in retirement', min:10, max:30, step:1, suffix:' years', value:20 }
    ],
    calculation: v => Math.max(0, (v.desired - v.forecast) * 12 * v.years),
    gapLabel: v => `S$${number(v.desired - v.forecast)}/month`,
    formula: v => `S$${number(v.desired)} desired monthly income − S$${number(v.forecast)} forecast income × 12 months × ${v.years} years`,
    types: [['Retirement income planning','Explore how a future income target, existing assets and protection can work together.'], ['Health and long-term care review','Understand how care or medical costs may affect retirement plans.'], ['Legacy planning','Consider how a plan can support the people and causes important to you.']],
    products: [['PRUWealth Plus (SGD)','A flexible wealth-planning plan described by SC Singapore as supporting changing financial needs and family goals.','Retirement and family goals'], ['PRUActive Retirement II','An SC Singapore retirement solution to explore with an adviser.','Retirement planning']],
    handoff: 'Request a retirement planning conversation'
  },
  alex: {
    name: 'Alex', initials: 'A', title: 'Your family protection review', icon: '✚',
    nudge: 'Based on your income, mortgage, dependants and cover we currently know about, a serious illness could leave an illustrative S$270k household funding gap.',
    summary: 'Your commitments have changed. Explore what an interruption to income could mean for your household finances.',
    signals: ['A mortgage and family commitments are visible in this illustrative customer profile.', 'The household funding horizon uses five years of essential costs.', 'Known protection is lower than the calculated support, debt and recovery scenario.'],
    fields: [
      { key:'costs', label:'Essential monthly household costs', min:3000, max:10000, step:500, prefix:'S$', value:6400 },
      { key:'mortgage', label:'Mortgage or debt to protect', min:50000, max:400000, step:10000, prefix:'S$', value:180000 },
      { key:'cover', label:'Existing protection recognised', min:0, max:600000, step:10000, prefix:'S$', value:324000 }
    ],
    calculation: v => Math.max(0, (v.costs * 60) + v.mortgage + 30000 - v.cover),
    gapLabel: () => 'household funding gap',
    formula: v => `S$${number(v.costs)} monthly costs × 60 months + S$${number(v.mortgage)} debt + S$30,000 recovery reserve − S$${number(v.cover)} existing cover`,
    types: [['Income continuity','Explore protection designed to help a family manage loss of income from illness, disability or accident.'], ['Mortgage protection','Review how family housing commitments could be supported.'], ['Critical illness and health','Understand the different roles of medical and critical-illness cover.']],
    products: [['PRUActive Term','An SC Singapore protection option described as flexible coverage for changing lifestyles.','Protection discussion'], ['Allianz Cancer Protect','An SC Singapore critical-illness option to discuss in the context of Alex’s broader needs.','Critical illness discussion']],
    handoff: 'Request a protection review'
  },
  sarah: {
    name: 'Sarah', initials: 'S', title: 'Your family goal outlook', icon: '♡',
    nudge: 'Based on a new dependant and the education savings we currently know about, this illustrative scenario shows a future education funding gap of S$34k.',
    summary: 'A new family priority can change how you balance education, protection and your own long-term goals.',
    signals: ['A new dependant has been included in this synthetic scenario.', 'An education objective and current savings have been added to the family view.', 'Future planned savings do not fully meet the illustrative education target.'],
    fields: [
      { key:'goal', label:'Future education goal', min:60000, max:220000, step:5000, prefix:'S$', value:120000 },
      { key:'funds', label:'Existing education funds', min:0, max:120000, step:2000, prefix:'S$', value:46000 },
      { key:'savings', label:'Projected future savings', min:0, max:100000, step:2000, prefix:'S$', value:40000 }
    ],
    calculation: v => Math.max(0, v.goal - v.funds - v.savings),
    gapLabel: () => 'future education gap',
    formula: v => `S$${number(v.goal)} education goal − S$${number(v.funds)} current funds − S$${number(v.savings)} projected savings`,
    types: [['Education savings','Explore a goal, time horizon and the role of regular savings.'], ['Family protection','Consider how a parent’s ability to provide could affect the goal.'], ['Legacy and guardianship','Start a broader conversation about family security and intentions.']],
    products: [['PRUActive Saver III','An SC Singapore customisable insurance-savings plan presented for life milestones.','Family milestone planning'], ['PRUWealth Plus (SGD)','A wealth-planning option to explore for longer-term family goals.','Family goals discussion']],
    handoff: 'Request a family-planning conversation'
  }
};

const person = people[currentPersona];
const defaults = Object.fromEntries(person.fields.map(field => [field.key, field.value]));
const initialView = currentPersona === 'alex' ? 'email' : currentPersona === 'sarah' ? 'banking' : 'lock';
let state = { values: {...defaults}, view: initialView, tab: 'overview', response: null, booking: false, assistant: false, chat: [], notificationVisible: false, pushVisible: false, customValues: false };
let notificationTimer = null;
let pushTimer = null;
const number = value => new Intl.NumberFormat('en-SG').format(Math.round(value));
const gap = () => person.calculation(state.values);
const route = view => { state.view = view; state.tab = 'overview'; render(); };

function lockScreen() {
  return `<div class="lock-screen"><div class="lock-status"><span>9:41</span><span>▮▮▮ ◔ ▰</span></div><div class="lock-content"><span class="lock-lock">⌁</span><div class="lock-time">9:41</div><div class="lock-date">Monday, 7 September</div>${state.pushVisible ? `<button class="push-card push-arrived" data-action="unlock" aria-label="Open SC Mobile notification"><div class="push-app"><img src="assets/scb/sc-wordmark.png" alt="Standard Chartered" /></div><div class="push-copy"><div><strong>SC Mobile</strong><span>now</span></div><b>${person.title}</b><p>${person.nudge}</p></div></button><p class="tap-hint">Tap notification to open</p>` : ''}</div></div>`;
}

function emailScreen() {
  return `<div class="email-screen"><header class="email-status"><span>9:41</span><span>▮▮▮ ◔ ▰</span></header><div class="email-toolbar"><button>‹</button><b>Inbox</b><span>•••</span></div><article class="email-message"><div class="email-sender"><div class="mail-mark"><img src="assets/scb/sc-wordmark.png" alt="Standard Chartered"/></div><div><b>SC Mobile</b><small>to Alex · now</small></div><button>⌄</button></div><h1>Alex, we identified a potential protection gap</h1><p class="email-preheader">A new Portfolio Intelligence insight is ready for your review.</p><div class="email-divider"></div><p>Hi Alex,</p><p>Based on the mortgage, family commitments and protection information currently included in your SC Mobile profile, our illustrative analysis indicates that there may be a gap in the funds available to support your household if income were interrupted for an extended period.</p><p>We have prepared a tailored review to help you understand the factors behind this finding, explore the potential impact, and consider suitable next steps. You can correct any information that is out of date before deciding whether a conversation would be useful.</p><div class="email-callout"><span>Portfolio Intelligence</span><b>Review your illustrative family protection outlook</b><small>See the gap we identified, the information used, and recommended next actions.</small></div><button class="email-cta" data-action="open">Review my outlook in SC Mobile</button><p class="email-fine">This message is part of an illustrative prototype. It does not contain a recommendation, quote or application outcome.</p></article></div>`;
}

function bankingHome() {
  return `<div class="screen banking-home"><header class="banking-header"><div class="sc-app-status"><span>11:28</span><span>▮▮▮ ◔ ▰</span></div><div class="sc-header-actions"><div></div><div><button class="sc-icon" aria-label="Notifications">♧<i></i></button><button class="sc-icon" aria-label="Messages">▢</button><button class="logout">Logout</button></div></div><h1>Pay &amp; Transfer</h1></header><div class="banking-body"><section class="transfer-panel"><div class="transfer-option">${scIcon('accounts')}<b>Between<br>My Accounts</b></div><div class="transfer-option">${scIcon('paynow')}<b>PayNow</b></div><div class="transfer-option">${scIcon('scan')}<b>Scan<br>&amp; Pay</b></div><div class="transfer-option">${scIcon('transfer')}<b>Local<br>Transfer</b></div><div class="transfer-option">${scIcon('globe')}<b>International<br>Transfer</b></div><div class="transfer-option">${scIcon('card')}<b>Pay All<br>Credit Cards</b></div></section><div class="transfer-pills"><button>${scIcon('bill')}Pay Bills</button><button>${scIcon('person')}Add Payees</button><button>${scIcon('receipt')}EasyBill</button></div><nav class="transfer-tabs"><button>My Payees</button><button class="selected">Transactions</button><button>Scheduled</button><button>Manage</button></nav><h2>12 Feb 2025</h2>${[1,2,3].map(() => `<div class="transaction-row"><span>▯</span><i></i><b>SGD 0.01</b></div>`).join('')}</div>${state.notificationVisible ? `<button class="in-app-pop notification-arrived" data-action="open" aria-label="Open new Portfolio Intelligence insight"><span class="notification-logo"><img src="assets/scb/sc-wordmark.png" alt=""/></span><span class="notification-copy"><small>SC Mobile · now</small><b>Portfolio Intelligence</b><strong>Sarah, a new family-goal insight is ready.</strong></span><span class="notification-chevron">›</span></button>` : ''}</div>`;
}

function scIcon(type) { const paths={paynow:'<path d="M8 12h8M12 8l4 4-4 4M16 18H8M12 22l-4-4 4-4"/>',invest:'<path d="M12 4l5 4v12H7V8l5-4Zm0 5v7m-3-4h6"/>',insights:'<path d="M9 18h6m-5 3h4M8.5 15.5A6 6 0 1 1 15.5 15.5L14 18h-4l-1.5-2.5Z"/>',refer:'<path d="M8 19V9a2 2 0 0 1 4 0v5m0-3a2 2 0 0 1 4 0v2m0-1a2 2 0 0 1 4 0v5c0 3-2 5-5 5h-3c-2 0-4-1-5-3l-2-4a2 2 0 0 1 3-2l1 1"/>',accounts:'<path d="M7 8h10v12H7zM10 5h7v12M9 12h6"/>',scan:'<path d="M8 4H4v4m12-4h4v4M4 16v4h4m12-4v4h-4M8 12h8"/>',transfer:'<path d="M5 9h12m-3-3 3 3-3 3M19 15H7m3 3-3-3 3-3"/>',globe:'<circle cx="12" cy="12" r="8"/><path d="M4 12h16M12 4c2 2 3 5 3 8s-1 6-3 8c-2-2-3-5-3-8s1-6 3-8"/>',card:'<rect x="4" y="7" width="16" height="10" rx="2"/><path d="M4 11h16m-9 3h3"/>',bill:'<path d="M7 4h10v16l-2-1-3 1-3-1-2 1V4Zm3 5h4m-4 3h4"/>',person:'<circle cx="12" cy="8" r="3"/><path d="M5 20c1-4 3-6 7-6s6 2 7 6M18 7v4m-2-2h4"/>',receipt:'<path d="M7 4h10v16l-2-1-3 1-3-1-2 1V4Zm3 5h4m-4 3h4"/>'}; return `<span class="sc-line-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round">${paths[type] || paths.insights}</svg></span>`; }
function quickActions() { return `<div class="quick-actions-row"><button>${scIcon('paynow')}PayNow</button><button>${scIcon('invest')}SC Invest</button><button data-action="open">${scIcon('insights')}Insights</button><button>${scIcon('refer')}Refer</button></div>`; }

function mobileHome() {
  const response = state.response === 'defer' ? 'Reminder saved for this demonstrator session.' : state.response === 'decline' ? 'This insight is hidden for this demonstrator session.' : null;
  return `<div class="screen sc-home"><header class="sc-header"><div class="sc-app-status"><span>9:41</span><span>▮▮▮ ◔ ▰</span></div><div class="sc-header-actions"><img src="assets/scb/sc-wordmark.png" alt="Standard Chartered"/><div><button class="sc-icon" aria-label="Notifications">♧<i></i></button><button class="sc-icon" aria-label="Messages">▢</button><button class="logout">Logout</button></div></div></header><div class="sc-content"><h1>Portfolio Intelligence</h1><p class="sc-subtitle">A clearer view of what matters to you</p><section class="sc-promo-card"><span class="promo-kicker">SC Mobile insight</span><h2>Make your financial picture work harder for you</h2><p>Explore relevant insights from across your accounts, goals and protection.</p><button data-action="open">Explore insights</button><span class="promo-orb orb-one"></span><span class="promo-orb orb-two"></span></section>${quickActions()}${response ? `<div class="sc-state">${response}<button data-action="reset">Reset demo</button></div>` : `<button class="in-app-notification" data-action="open"><span class="insight-dot">✦</span><span><b>New in Portfolio Intelligence</b><small>${person.title} · View your illustrative outlook</small></span><span class="chevron">›</span></button>`}<section class="assets-card"><div class="assets-title"><b>Total Assets</b><span>ⓘ</span><button aria-label="Hide balances">⌧</button></div><div class="asset-row"><span class="asset-green"></span><div><b>Deposits</b><small>Total Balance</small></div><strong>SGD 83,000.00</strong><span>⌃</span></div><div class="asset-actions"><button>⇆ Make a Transfer</button><button>◴ Transactions</button></div><div class="account-row"><b>FC Cheque &amp; Save A/C</b><span>Current Balance</span><strong>USD 0.00</strong></div></section></div></div>`;
}

function assumptions() {
  return `<div class="scenario-controls">${person.fields.map((field,index) => `<article class="scenario-control"><div class="scenario-number">0${index + 1}</div><div class="scenario-copy"><label for="${field.key}">${field.label}</label><small>Adjust to explore the impact on this illustrative view.</small></div><output id="out-${field.key}">${field.prefix || ''}${number(state.values[field.key])}${field.suffix || ''}</output><input id="${field.key}" data-field="${field.key}" type="range" min="${field.min}" max="${field.max}" step="${field.step}" value="${state.values[field.key]}" /><div class="scenario-edit"><span>Set amount</span><div><span>${field.prefix || ''}</span><input data-field="${field.key}" type="number" min="${field.min}" max="${field.max}" step="${field.step}" value="${state.values[field.key]}" aria-label="${field.label}" /><span>${field.suffix || ''}</span></div></div></article>`).join('')}</div>`;
}

function overview() { return `<article class="card panel"><span class="panel-kicker">What we noticed</span><h2>${person.title}</h2><p>${person.summary}</p><div class="signal-list">${person.signals.map(signal => `<div class="signal"><span class="tick">✓</span><span>${signal}</span></div>`).join('')}</div></article><article class="card panel"><h3>Choose how you would like to explore</h3><p>Use the guided view for a quick walkthrough, or ask Portfolio Intelligence a question in your own words.</p><div class="actions"><button class="primary" data-action="tab" data-tab="assumptions">Explore your scenario</button><button class="secondary" data-action="assistant">Ask Portfolio Intelligence</button><button class="quiet" data-action="defer">Remind me later</button><button class="quiet" data-action="decline">Not for me</button></div></article>`; }
function assumptionsPanel() { return `<article class="card panel scenario-panel"><span class="panel-kicker">Your scenario</span><h2>See what changes the picture</h2><p>Adjust a few details to see the immediate impact. These are synthetic illustrative figures, not a quote or recommendation.</p><div class="formula"><strong>How this view is calculated</strong><br>${person.formula(state.values)}<br><strong>Illustrative gap: S$${number(gap())}</strong></div>${assumptions()}<div class="actions"><button class="primary" data-action="tab" data-tab="options">See ways forward</button><button class="secondary" data-action="assistant">Ask about this scenario</button></div></article>`; }
function options() { return `<article class="card panel"><span class="panel-kicker">Ways forward</span><h2>Start with the right conversation</h2><p>These are areas to consider after understanding the need; they are not ranked offers.</p>${person.types.map(item => `<div class="choice"><span class="choice-icon">→</span><div><strong>${item[0]}</strong><small>${item[1]}</small></div></div>`).join('')}</article><article class="card panel products-panel"><h2>Products to explore with an adviser</h2><p>These public SC Singapore product references are illustrative starting points. Terms, suitability and availability require adviser review.</p>${person.products.map((item,index) => `<div class="card product product-card"><div class="product-visual product-visual-${index}">${scIcon(index === 0 ? 'invest' : 'card')}</div><div class="product-body"><span class="badge">${item[2]}</span><h3>${item[0]}</h3><p>${item[1]}</p><button data-action="detail">Explore this option</button></div></div>`).join('')}<div class="actions"><button class="primary" data-action="book">${person.handoff}</button><button class="secondary" data-action="assistant">Ask Portfolio Intelligence</button></div></article>`; }
function assistantPanel() { const opening = `I’m your Portfolio Intelligence guide. Based on the information in this illustrative scenario, we identified a potential S$${number(gap())} ${person.gapLabel(state.values)}. I can explain what contributed to it, show what changes the picture, and help you choose a next step such as exploring options or speaking with an adviser.`; const conversation = [{role:'assistant',text:opening},...state.chat]; const ready = state.chat.some(message => message.role === 'user' && message.text === 'What could I do next?'); return `<section class="assistant-sheet" role="dialog" aria-modal="true" aria-label="Portfolio Intelligence conversation"><div class="assistant-panel"><div class="assistant-head"><div class="assistant-mark">✦</div><div><span>Portfolio Intelligence</span><b>Your optional guide</b></div><button data-action="assistant-close" aria-label="Close assistant">×</button></div><div class="chat-stream">${conversation.map(message => `<div class="chat-bubble ${message.role}">${message.text}</div>`).join('')}</div><div class="assistant-prompts"><button data-action="ask" data-prompt="why">Why did you identify this gap?</button><button data-action="ask" data-prompt="change">Show me what changes the outcome</button><button data-action="ask" data-prompt="next">What could I do next?</button></div>${ready ? `<button class="chat-cta" data-action="chat-continue">See ways forward</button>` : ''}<p>This optional assistant uses demonstrator data and is not financial advice.</p></div></section>`; }
function journey() { const content = state.tab === 'overview' ? overview() : state.tab === 'assumptions' ? assumptionsPanel() : options(); return `<div class="screen"><header class="journey-top"><button class="back" data-action="home" aria-label="Back to home">‹</button><span class="journey-title">Portfolio Intelligence</span><button class="reset" data-action="reset">Reset</button></header><div class="journey"><div class="notice">Illustrative prototype using synthetic customer data. It does not provide a quote, recommendation, underwriting or eligibility outcome.</div><section class="hero"><span class="eyebrow">${person.name}'s portfolio insight</span><h1>${person.title}</h1><p>${person.summary}</p><div class="gap-number"><b>S$${number(gap())}</b><span>${person.gapLabel(state.values)}<br>based on current assumptions</span></div><button class="hero-assistant" data-action="assistant">✦ Ask Portfolio Intelligence</button></section><nav class="tabs" aria-label="Insight sections"><button class="${state.tab === 'overview' ? 'active':''}" data-action="tab" data-tab="overview">Your outlook</button><button class="${state.tab === 'assumptions' ? 'active':''}" data-action="tab" data-tab="assumptions">Your scenario</button><button class="${state.tab === 'options' ? 'active':''}" data-action="tab" data-tab="options">Ways forward</button></nav>${state.booking ? booking() : content}</div></div>${state.assistant ? assistantPanel() : ''}`; }
function booking() { return `<article class="card booking"><div class="booking-icon">✓</div><span class="eyebrow">Conversation request received</span><h2>We will be in touch to arrange your review</h2><p>An SC Wealth Planning specialist will contact ${person.name} through the preferred channel on file to arrange a conversation about the illustrative scenario. The details explored here will help start that discussion.</p><div class="booking-next"><b>What happens next</b><span>1. We confirm a suitable time</span><span>2. You review your goals with a specialist</span><span>3. Any product discussion follows the required fact-find</span></div><p class="booking-fine">This is a demonstrator confirmation only—no real contact request has been submitted.</p><div class="actions"><button class="primary" data-action="home">Return to SC Mobile</button><button class="quiet" data-action="reset">Reset demo</button></div></article>`; }
function nav() { return `<nav class="bottom-nav rebuilt-nav" aria-label="Primary navigation"><button class="nav-link active" data-action="home"><span>⌂</span>Home</button><button class="nav-link"><span>⇆</span>Pay &amp; Transfer</button><button class="nav-link" data-action="open"><span>▥</span>Invest &amp; Insure</button><button class="nav-link"><span>◌</span>Discover</button><button class="nav-link"><span>▢</span>Services</button></nav>`; }
function render() { if (state.view !== 'banking' && notificationTimer) { clearTimeout(notificationTimer); notificationTimer = null; } if (state.view !== 'lock' && pushTimer) { clearTimeout(pushTimer); pushTimer = null; } app.innerHTML = state.view === 'lock' ? lockScreen() : state.view === 'email' ? emailScreen() : state.view === 'banking' ? bankingHome() + nav() : (state.view === 'home' ? mobileHome() : journey()) + nav(); if (state.view === 'banking' && !state.notificationVisible && !notificationTimer) { notificationTimer = setTimeout(() => { notificationTimer = null; if (state.view === 'banking' && !state.notificationVisible) { state.notificationVisible = true; render(); } }, 900); } if (state.view === 'lock' && !state.pushVisible && !pushTimer) { pushTimer = setTimeout(() => { pushTimer = null; if (state.view === 'lock' && !state.pushVisible) { state.pushVisible = true; render(); } }, 900); } }

app.addEventListener('click', event => {
  const target = event.target.closest('[data-action]'); if (!target) return;
  const action = target.dataset.action;
  if (action === 'open') route('journey');
  if (action === 'unlock') { state.view = 'home'; render(); }
  if (action === 'home') { state.view = 'home'; state.booking = false; render(); }
  if (action === 'tab') { state.tab = target.dataset.tab; state.booking = false; state.assistant = false; render(); }
  if (action === 'defer' || action === 'decline') { state.response = action; state.view = 'home'; render(); }
  if (action === 'reset') { state = { values:{...defaults}, view:initialView, tab:'overview', response:null, booking:false,assistant:false,chat:[],notificationVisible:false,pushVisible:false,customValues:false }; render(); }
  if (action === 'book') { state.booking = true; render(); }
  if (action === 'assistant') { state.assistant = true; render(); }
  if (action === 'assistant-close') { state.assistant = false; render(); }
  if (action === 'chat-continue') { state.assistant = false; state.tab = 'options'; render(); }
  if (action === 'ask') { const prompts = { why:'Why did you identify this gap?', change:'Show me what changes the outcome', next:'What could I do next?' }; const replies = { why: `We identified this as a potential gap because ${person.signals[0].toLowerCase()} ${person.signals[1]} The result is illustrative and you can review every input in “Your outlook”.`, change: `The largest drivers are shown in “Your scenario”. Try adjusting one card at a time—the illustrative gap refreshes immediately so you can see what makes the greatest difference.`, next: `There are three appropriate next steps: explore the solution areas, review the public product references with an adviser, or request a conversation with an SC Wealth Planning specialist. You remain in control.` }; state.chat.push({role:'user',text:prompts[target.dataset.prompt]},{role:'assistant',text:replies[target.dataset.prompt]}); state.assistant = true; render(); }
  if (action === 'detail') { state.tab = 'options'; alert('Demonstration only: product terms, suitability, availability and any application would be confirmed with an authorised adviser.'); }
});
app.addEventListener('input', event => { const key = event.target.dataset.field; if (!key || event.target.value === '') return; const field = person.fields.find(item => item.key === key); state.values[key] = Math.max(field.min, Math.min(field.max, Number(event.target.value))); state.customValues = true; document.querySelectorAll(`[data-field="${key}"]`).forEach(input => { if (input !== event.target) input.value = state.values[key]; }); const out = document.querySelector(`#out-${key}`); if(out) out.textContent = `${field.prefix || ''}${number(state.values[key])}${field.suffix || ''}`; const formula = event.target.closest('.panel')?.querySelector('.formula'); if(formula) formula.innerHTML = `<strong>Calculation:</strong><br>${person.formula(state.values)}<br><strong>Illustrative gap: S$${number(gap())}</strong>`; const heroNumber = document.querySelector('.gap-number b'); if(heroNumber) heroNumber.textContent = `S$${number(gap())}`; });
render();
